// Schema creation runs after the existing users table is available.
export const sqliteRequestSchema = `CREATE TABLE IF NOT EXISTS customer_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  subject TEXT NOT NULL CHECK(length(trim(subject)) BETWEEN 1 AND 150),
  message TEXT NOT NULL CHECK(length(trim(message)) BETWEEN 1 AND 5000),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK(status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS customer_requests_user_idx ON customer_requests(user_id);`;

export const postgresRequestSchema = `CREATE TABLE IF NOT EXISTS customer_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  subject TEXT NOT NULL CHECK(length(trim(subject)) BETWEEN 1 AND 150),
  message TEXT NOT NULL CHECK(length(trim(message)) BETWEEN 1 AND 5000),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK(status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS customer_requests_user_idx ON customer_requests(user_id);`;
