import type { Pool } from "pg";
import { postgresRequestSchema } from "../requests/schema.ts";

const initialTools = [
  ["Task Simplifier", "Turn a long or overwhelming task into smaller, clearer steps."],
  ["Daily Priorities", "Choose what matters most today and keep important tasks visible."],
  ["Routine Builder", "Create simple repeatable routines without complicated setup."],
  ["Reminder Tool", "Keep track of important tasks and reminders in one clear place."],
];

export async function initializePostgres(pool: Pool) {
  const db = await pool.connect();
  try {
    await db.query("BEGIN");
    // Serialize startup so concurrent instances cannot seed the same fresh database.
    await db.query("SELECT pg_advisory_xact_lock(847201)");
    const exists = await db.query("SELECT to_regclass('public.tools') AS table_name");
    await db.query(`
      CREATE TABLE IF NOT EXISTS inquiries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL, email TEXT NOT NULL, subject TEXT NOT NULL,
        message TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS tools (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL, description TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS clients (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL, email TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX IF NOT EXISTS clients_email_lower_unique ON clients (lower(email));
      CREATE TABLE IF NOT EXISTS subscriptions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
        tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE RESTRICT,
        status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'cancelled')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (client_id, tool_id)
      );
      CREATE INDEX IF NOT EXISTS idx_subscriptions_tool ON subscriptions(tool_id);
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL, email TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON users (lower(email));
      CREATE TABLE IF NOT EXISTS sessions (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        expires_at TIMESTAMPTZ NOT NULL
      );
      CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions(expires_at);
      CREATE TABLE IF NOT EXISTS auth_attempts (
        key TEXT PRIMARY KEY,
        attempts INTEGER NOT NULL DEFAULT 0,
        window_start TIMESTAMPTZ NOT NULL DEFAULT now()
      );
    `);
    await db.query(postgresRequestSchema);
    if (!exists.rows[0].table_name) {
      for (const [title, description] of initialTools) {
        await db.query("INSERT INTO tools (title, description) VALUES ($1, $2)", [title, description]);
      }
    }
    await db.query("COMMIT");
  } catch (error) {
    await db.query("ROLLBACK");
    throw error;
  } finally {
    db.release();
  }
}

