import express, { type ErrorRequestHandler } from "express";
import type { Pool } from "pg";
import { registerPostgresAuth } from "./auth-postgres.ts";

const initialTools = [
  ["Task Simplifier", "Turn a long or overwhelming task into smaller, clearer steps."],
  ["Daily Priorities", "Choose what matters most today and keep important tasks visible."],
  ["Routine Builder", "Create simple repeatable routines without complicated setup."],
  ["Reminder Tool", "Keep track of important tasks and reminders in one clear place."],
];

export async function initializePostgres(pool: Pool) {
  const db = await pool.connect();
  try {
    await db.query("BEGIN");
    // Serialize startup so concurrent instances cannot seed the same fresh database.
    await db.query("SELECT pg_advisory_xact_lock(847201)");
    const exists = await db.query("SELECT to_regclass('public.tools') AS table_name");
    await db.query(`
      CREATE TABLE IF NOT EXISTS inquiries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL, email TEXT NOT NULL, subject TEXT NOT NULL,
        message TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS tools (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL, description TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS clients (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL, email TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX IF NOT EXISTS clients_email_lower_unique ON clients (lower(email));
      CREATE TABLE IF NOT EXISTS subscriptions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
        tool_id INTEGER NOT NULL REFERENCES tools(id) ON DELETE RESTRICT,
        status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'cancelled')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (client_id, tool_id)
      );
      CREATE INDEX IF NOT EXISTS idx_subscriptions_tool ON subscriptions(tool_id);
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL, email TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON users (lower(email));
      CREATE TABLE IF NOT EXISTS sessions (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        expires_at TIMESTAMPTZ NOT NULL
      );
      CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions(expires_at);
      CREATE TABLE IF NOT EXISTS auth_attempts (
        key TEXT PRIMARY KEY,
        attempts INTEGER NOT NULL DEFAULT 0,
        window_start TIMESTAMPTZ NOT NULL DEFAULT now()
      );
    `);
    if (!exists.rows[0].table_name) {
      for (const [title, description] of initialTools) {
        await db.query("INSERT INTO tools (title, description) VALUES ($1, $2)", [title, description]);
      }
    }
    await db.query("COMMIT");
  } catch (error) {
    await db.query("ROLLBACK");
    throw error;
  } finally {
    db.release();
  }
}

const validId = (value: unknown): value is number =>
  typeof value === "number" && Number.isSafeInteger(value) && value > 0;
const routeId = (value: string | undefined) => Number(value);
const toolError = (title: unknown, description: unknown) => {
  if (typeof title !== "string" || typeof description !== "string" || !title.trim() || !description.trim())
    return "Title and description are required.";
  if (title.trim().length > 100 || description.trim().length > 1000)
    return "Keep the title under 101 characters and description under 1001 characters.";
  return "";
};
const clientError = (name: unknown, email: unknown) => {
  if (typeof name !== "string" || !name.trim() || name.trim().length > 100)
    return "Enter a client name of 1–100 characters.";
  if (typeof email !== "string" || email.trim().length > 254 ||
      !/^[^\s@]+@[^\s@.]+(?:\.[^\s@.]+)+$/.test(email.trim()))
    return "Enter a valid email address.";
  return "";
};
const subscriptionError = (clientId: unknown, toolId: unknown, status: unknown) => {
  if (!validId(clientId) || !validId(toolId)) return "Choose an existing client and tool.";
  if (status !== "active" && status !== "cancelled") return "Status must be active or cancelled.";
  return "";
};

const subscriptionSelect = `SELECT subscriptions.*, clients.name AS client_name,
  clients.email AS client_email, tools.title AS tool_title
  FROM subscriptions JOIN clients ON clients.id = subscriptions.client_id
  JOIN tools ON tools.id = subscriptions.tool_id`;

export function createPostgresApp(db: Pool) {
  const app = express();
  app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    res.header("Access-Control-Allow-Headers", "Content-Type");
    if (req.method === "OPTIONS") return res.sendStatus(204);
    next();
  });
  app.use(express.json());
  registerPostgresAuth(app, db);
  app.get("/", (_req, res) => res.send("Nuvra backend is running"));

  app.post("/api/contact", async (req, res) => {
    const { name, email, subject, message } = req.body ?? {};
    if ([name, email, subject, message].some(v => typeof v !== "string" || !v.trim()))
      return res.status(400).json({ error: "All fields are required" });
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))
      return res.status(400).json({ error: "Please provide a valid email address" });
    try {
      await db.query("INSERT INTO inquiries (name, email, subject, message) VALUES ($1, $2, $3, $4)",
        [name.trim(), email.trim(), subject.trim(), message.trim()]);
      return res.status(201).json({ message: "Inquiry received successfully" });
    } catch {
      return res.status(500).json({ error: "Could not save inquiry" });
    }
  });

  app.get("/api/tools", async (_req, res) => {
    res.set("Cache-Control", "no-store");
    res.json((await db.query("SELECT * FROM tools ORDER BY id")).rows);
  });
  app.post("/api/tools", async (req, res) => {
    const { title, description } = req.body ?? {};
    const error = toolError(title, description);
    if (error) return res.status(400).json({ error });
    const result = await db.query("INSERT INTO tools (title, description) VALUES ($1, $2) RETURNING *",
      [title.trim(), description.trim()]);
    res.status(201).json(result.rows[0]);
  });
  app.put("/api/tools/:id", async (req, res) => {
    const id = routeId(req.params.id);
    if (!validId(id)) return res.status(400).json({ error: "Invalid tool ID." });
    const { title, description } = req.body ?? {};
    const error = toolError(title, description);
    if (error) return res.status(400).json({ error });
    const result = await db.query(`UPDATE tools SET title = $1, description = $2,
      updated_at = now() WHERE id = $3 RETURNING *`, [title.trim(), description.trim(), id]);
    if (!result.rowCount) return res.status(404).json({ error: "Tool not found. Refresh the list and try again." });
    res.json(result.rows[0]);
  });
  app.delete("/api/tools/:id", async (req, res) => {
    const id = routeId(req.params.id);
    if (!validId(id)) return res.status(400).json({ error: "Invalid tool ID." });
    const result = await db.query("DELETE FROM tools WHERE id = $1", [id]);
    if (!result.rowCount) return res.status(404).json({ error: "Tool not found. Refresh the list and try again." });
    res.status(204).end();
  });

  app.get("/api/clients", async (_req, res) => {
    res.set("Cache-Control", "no-store");
    res.json((await db.query("SELECT * FROM clients ORDER BY id")).rows);
  });
  app.post("/api/clients", async (req, res) => {
    const { name, email } = req.body ?? {};
    const error = clientError(name, email);
    if (error) return res.status(400).json({ error });
    const result = await db.query("INSERT INTO clients (name, email) VALUES ($1, $2) RETURNING *",
      [name.trim(), email.trim().toLowerCase()]);
    res.status(201).json(result.rows[0]);
  });
  app.put("/api/clients/:id", async (req, res) => {
    const id = routeId(req.params.id);
    if (!validId(id)) return res.status(400).json({ error: "Invalid client ID." });
    const { name, email } = req.body ?? {};
    const error = clientError(name, email);
    if (error) return res.status(400).json({ error });
    const result = await db.query(`UPDATE clients SET name = $1, email = $2,
      updated_at = now() WHERE id = $3 RETURNING *`, [name.trim(), email.trim().toLowerCase(), id]);
    if (!result.rowCount) return res.status(404).json({ error: "Client not found." });
    res.json(result.rows[0]);
  });
  app.delete("/api/clients/:id", async (req, res) => {
    const id = routeId(req.params.id);
    if (!validId(id)) return res.status(400).json({ error: "Invalid client ID." });
    const result = await db.query("DELETE FROM clients WHERE id = $1", [id]);
    if (!result.rowCount) return res.status(404).json({ error: "Client not found." });
    res.status(204).end();
  });

  app.get("/api/subscriptions", async (_req, res) => {
    res.set("Cache-Control", "no-store");
    res.json((await db.query(subscriptionSelect + " ORDER BY subscriptions.id")).rows);
  });
  app.post("/api/subscriptions", async (req, res) => {
    const { client_id, tool_id, status } = req.body ?? {};
    const error = subscriptionError(client_id, tool_id, status);
    if (error) return res.status(400).json({ error });
    const result = await db.query(`INSERT INTO subscriptions (client_id, tool_id, status)
      VALUES ($1, $2, $3) RETURNING id`, [client_id, tool_id, status]);
    const record = await db.query(subscriptionSelect + " WHERE subscriptions.id = $1", [result.rows[0].id]);
    res.status(201).json(record.rows[0]);
  });
  app.put("/api/subscriptions/:id", async (req, res) => {
    const id = routeId(req.params.id);
    if (!validId(id)) return res.status(400).json({ error: "Invalid subscription ID." });
    const { client_id, tool_id, status } = req.body ?? {};
    const error = subscriptionError(client_id, tool_id, status);
    if (error) return res.status(400).json({ error });
    const result = await db.query(`UPDATE subscriptions SET client_id = $1, tool_id = $2,
      status = $3, updated_at = now() WHERE id = $4 RETURNING id`, [client_id, tool_id, status, id]);
    if (!result.rowCount) return res.status(404).json({ error: "Subscription not found." });
    const record = await db.query(subscriptionSelect + " WHERE subscriptions.id = $1", [id]);
    res.json(record.rows[0]);
  });
  app.delete("/api/subscriptions/:id", async (req, res) => {
    const id = routeId(req.params.id);
    if (!validId(id)) return res.status(400).json({ error: "Invalid subscription ID." });
    const result = await db.query("DELETE FROM subscriptions WHERE id = $1", [id]);
    if (!result.rowCount) return res.status(404).json({ error: "Subscription not found." });
    res.status(204).end();
  });

  const handleError: ErrorRequestHandler = (error, _req, res, _next) => {
    if (error?.code === "23505") return res.status(409).json({
      error: "That email or client–tool subscription already exists. Edit the existing record instead.",
    });
    if (error?.code === "23503") return res.status(409).json({
      error: "This record is linked to another table. Choose an existing client/tool, or remove its subscriptions before deleting it.",
    });
    if (error?.code === "23514") return res.status(400).json({ error: "Invalid subscription status." });
    const malformed = error instanceof SyntaxError;
    console.error("API error", error);
    res.status(malformed ? 400 : 500).json({
      error: malformed ? "Send valid JSON." : "Something went wrong. Please try again.",
    });
  };
  app.use(handleError);
  return app;
}
